name: JMeter Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Start dummy app with Docker Compose
      run: |
        docker compose up -d --build
      working-directory: dummy-app

    - name: Wait for the API to be ready (using docker compose exec)
      run: |
        for i in {1..10}; do
          if docker compose exec app-dummy curl -s http://localhost:3000/api/ping | grep -q pong; then
            echo "API is up ✅"
            break
          fi
          echo "Waiting for API..."
          sleep 5
        done
      working-directory: dummy-app

    - name: Run JMeter test attached to Docker network
      run: |
        docker run --rm \
          --network dummy-app_jmeter-net \
          -v ${{ github.workspace }}/jmeter:/tests \
          -w /tests \
          justb4/jmeter \
          -n -t test-plan.jmx \
          -Jtarget_host=app-dummy \
          -l results.jtl \
          -e -o report

    - name: Upload JMeter HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-html-report
        path: jmeter/report
